### ISSUE TITLE
有没有指令帮助啥的

### ISSUE THREAD

**Issue by ShanShuWu** [bridgeL/nonebot-plugin-ayaka-games#1]
如题，请问合集中各组分的命令是什么，有些功能不知道怎么用

**Comment by bridgeL** [comment]
你的nonebot、nonebot-plugin-ayaka、nonebot-plugin-ayaka-games版本是多少？

建议版本
包名|版本
-|-
nonebot|2.0.0b5（rc的我没试过）
nonebot-plugin-ayaka| 0.3.5
nonebot-plugin-ayaka-games |0.1.3

**在此前提下**，你可以
指令|功能
-|-
#help|查看所有帮助
#help <插件名>|查看对应插件的详细帮助

注：#是nonebot的配置项 `command_start` 的值的第一个

```
COMMAND_START=["#"]
```

这是我个人常用的，你可以修改为你喜欢的

_修改了一下排版_

**Comment by ShanShuWu** [comment]
好的，感谢
