### ISSUE TITLE
报错empty separator

### ISSUE THREAD

**Issue by zuixiaoxiao** [bridgeL/nonebot-plugin-ayaka-games#7]
![image](https://user-images.githubusercontent.com/108536651/204072521-c0d68b89-7fb2-4385-bd40-fc83f334e2f6.png)
![image](https://user-images.githubusercontent.com/108536651/204072508-fe2bf58f-fde5-4d08-b4ae-297fbba0cc17.png)

**Comment by zuixiaoxiao** [comment]
nonebot版本rc1

**Comment by bridgeL** [comment]
感谢反馈

**解决方案**

请修改.env.dev文件（或者.env.prod，看你.env用的是哪个），设置分割符为空格，`COMMAND_SEP=[" "]`

**未来**

ayaka下一版本（0.4.3）会彻底修复此问题（当分割符为空时ayaka出现异常报错），同时ayaka_games也将更新至最新版

**Comment by zuixiaoxiao** [comment]
> 感谢反馈
> 
> **解决方案**
> 
> 请修改.env.dev文件（或者.env.prod，看你.env用的是哪个），设置分割符为空格，`COMMAND_SEP=[" "]`
> 
> **未来**
> 
> ayaka下一版本（0.4.3）会彻底修复此问题（当分割符为空时ayaka出现异常报错），同时ayaka_games也将更新至最新版

但这样就会出现我之前那个issues的报错

**Comment by bridgeL** [comment]
那没办法，如果设置分割符为空，ayaka_games中的一些功能都没法使用了（不是报错，而是无法使用）

有的功能需要你传入两个参数，比如：
A：`a b`
bot: 收到了`a`和`b`

如果不设置分割符，ayaka不会分割`a b`为`a`、`b`，该功能便无法使用

**Comment by zuixiaoxiao** [comment]
> 那没办法，如果设置分割符为空，ayaka_games中的一些功能都没法使用了（不是报错，而是无法使用）
> 
> 有的功能需要你传入两个参数，比如： A：`a b` bot: 收到了`a`和`b`
> 
> 如果不设置分割符，ayaka不会分割`a b`为`a`、`b`，该功能便无法使用

emm，那只能等你弄了，我改为空使用后就会和头像表情包这个冲突造成疯狂报错

**Comment by bridgeL** [comment]
哦抱歉，我差点忘了，ayaka可以单独设置分割符，而不使用全局的，你可以在.env.dev中写入 `ayaka_separate=" "`，刚才我测试了一下，可以用

.env.dev
```
ayaka_prefix="#"
ayaka_separate=" "
```

**Comment by zuixiaoxiao** [comment]
> 哦抱歉，我差点忘了，ayaka可以单独设置分割符，而不使用全局的，你可以在.env.dev中写入 `ayaka_separate=" "`，刚才我测试了一下，可以用

好，我试试

**Comment by zuixiaoxiao** [comment]
emm还是不行
![image](https://user-images.githubusercontent.com/108536651/204125721-8772eea9-b8e5-45e7-93ce-afd43a9ad054.png)
![image](https://user-images.githubusercontent.com/108536651/204125754-c298db5a-67ef-4e9e-aa19-b81ce3092f8a.png)

**Comment by bridgeL** [comment]
咦，可以看看你全部的配置吗（敏感信息除外）

**Comment by zuixiaoxiao** [comment]
HOST=0.0.0.0 # Nonebot监听的IP
PORT=13579 # Nonebot监听的端口
LOG_LEVEL=INFO # 日志等级
SUPERUSERS=[""] # 超级用户
NICKNAME=[ "派蒙" ] # 机器人的昵称
COMMAND_START=["", "/", "#"] # 命令前缀,根据需要自行修改
COMMAND_SEP=[""] # 命令分隔符，别动

"uin": "",
"password": ""
"protocol": "5"

setu_enable_private = True
setu_save =D:\LittlePaimon\LittlePaimon\data\setu4/img
setu_proxy = "i.pixiv.re"

RUSSIAN_PATH = ''         # 数据存储路径，默认路径是此插件目录下
SIGN_GOLD = [1, 1000]      # 每日签到可得到的金币范围
MAX_BET_GOLD = 1000       # 赌注的最大上限（防止直接梭哈白给天台见）

API_ROOT = 'http://127.0.0.1:5700'     #
RSS_PROXY = '127.0.0.1:7890'    # 代理地址
ROOTUSER=[]    # 管理员qq,支持多管理员，逗号分隔 如 [1,2,3] 注意，启动消息只发送给第一个管理员
DEBUG = False
RSSHUB='https://rss.itggg.cn/'     # rsshub订阅地址
DELCACHE=3     #缓存删除间隔 天 

# 是否开启禁言等操作的成功提示【不开启的话踢人/禁言等成功没有QQ消息提示】
callback_notice=true # 如果不想开启设置成 false 或者不添加此配置项【默认关闭】
send_group_id = [""]    # 必填 群号
send_mode = 1                 # 选填 默认模式2 模式1发送自定义句子，模式2随机调用一句
send_sentence_moring = ["早上好","起床起床干活了","又是充满希望的一天"]    # 如果是模式1 此项必填，早上随机发送该字段中的一句
send_sentence_night = ["晚安","累死了不玩了不玩了","睡觉睡觉"]     # 如果是模式1 此项必填，晚上随机发送该字段中的一句
send_time_moring = "6 0"    # 选填 早上发送时间默认为7:00
send_time_night = "23 0"    # 选填 晚上发送时间默认为22:00 
     
analysis_blacklist = [] # 不解析里面填写的QQ号发的链接 List[int]
analysis_display_image = true # 是否显示封面 true/false  

wenxin_ak = ""
wenxin_sk = ""
wenxin_cd_time = 300 # 技能冷却时间，以秒为单位
wenxin_image_count = 3 # 画画的图片数量
wenxin_manager_list = ["385442065"] # 管理员列表(不触发冷却时间限制)

CARTOON_FORWARD=true                 # 合并转发的形式发送消息
CARTOON_LENGTH=-1                      # 每次发送的数量，用-1表示全部取出
CARTOON_FORMANT="{title}\n{magnet}"   # 发送的消息格式化
CARTOON_ONESKIP=true                  # 当只有一个选项时跳过   

wordcloud_background_color= white

xiaoai_apikey = ""
Bot_NICKNAME = ""
Bot_MASTER = ""

ayaka_prefix="#"
ayaka_separate=" "

**Comment by zuixiaoxiao** [comment]
HOST=0.0.0.0 # Nonebot监听的IP
PORT=13579 # Nonebot监听的端口
LOG_LEVEL=INFO # 日志等级
SUPERUSERS=[""] # 超级用户
NICKNAME=[ "派蒙" ] # 机器人的昵称
COMMAND_START=["", "/", "#"] # 命令前缀,根据需要自行修改
COMMAND_SEP=[""] # 命令分隔符，别动

"uin": "",
"password": ""
"protocol": "5"

setu_enable_private = True
setu_save =D:\LittlePaimon\LittlePaimon\data\setu4/img
setu_proxy = "i.pixiv.re"

RUSSIAN_PATH = ''         # 数据存储路径，默认路径是此插件目录下
SIGN_GOLD = [1, 1000]      # 每日签到可得到的金币范围
MAX_BET_GOLD = 1000       # 赌注的最大上限（防止直接梭哈白给天台见）

API_ROOT = 'http://127.0.0.1:5700'     #
RSS_PROXY = '127.0.0.1:7890'    # 代理地址
ROOTUSER=[385442065]    # 管理员qq,支持多管理员，逗号分隔 如 [1,2,3] 注意，启动消息只发送给第一个管理员
DEBUG = False
RSSHUB='https://rss.itggg.cn/'     # rsshub订阅地址
DELCACHE=3     #缓存删除间隔 天 

# 是否开启禁言等操作的成功提示【不开启的话踢人/禁言等成功没有QQ消息提示】
callback_notice=true # 如果不想开启设置成 false 或者不添加此配置项【默认关闭】
send_group_id = ["955747418"]    # 必填 群号
send_mode = 1                 # 选填 默认模式2 模式1发送自定义句子，模式2随机调用一句
send_sentence_moring = ["早上好","起床起床干活了","又是充满希望的一天"]    # 如果是模式1 此项必填，早上随机发送该字段中的一句
send_sentence_night = ["晚安","累死了不玩了不玩了","睡觉睡觉"]     # 如果是模式1 此项必填，晚上随机发送该字段中的一句
send_time_moring = "6 0"    # 选填 早上发送时间默认为7:00
send_time_night = "23 0"    # 选填 晚上发送时间默认为22:00 
     
analysis_blacklist = [] # 不解析里面填写的QQ号发的链接 List[int]
analysis_display_image = true # 是否显示封面 true/false  

wenxin_ak = "
"
wenxin_sk = ""
wenxin_cd_time = 300 # 技能冷却时间，以秒为单位
wenxin_image_count = 3 # 画画的图片数量
wenxin_manager_list = "] # 管理员列表(不触发冷却时间限制)

CARTOON_FORWARD=true                 # 合并转发的形式发送消息
CARTOON_LENGTH=-1                      # 每次发送的数量，用-1表示全部取出
CARTOON_FORMANT="{title}\n{magnet}"   # 发送的消息格式化
CARTOON_ONESKIP=true                  # 当只有一个选项时跳过   

wordcloud_background_color= white

xiaoai_apikey = ""
Bot_NICKNAME = ""
Bot_MASTER = ""

ayaka_prefix="#"
ayaka_separate=" "

**Comment by zuixiaoxiao** [comment]
算就这样吧

**Comment by bridgeL** [comment]
好吧，可能其他地方还有问题，我没考虑到插件配置冲突的问题

最后，可以问一下你，下载本插件时主要是想使用哪个功能呢？

**Comment by zuixiaoxiao** [comment]
> 好吧，可能其他地方还有问题，我没考虑到插件配置冲突的问题
> 
> 最后，可以问一下你，下载本插件时主要是想使用哪个功能呢？

玩小游戏

**Comment by bridgeL** [comment]
抱歉，应该是ayaka的问题

ayaka的优先级是5

nonebot_plugin_petpet的优先级是12

ayaka在处理完消息后把错误地把消息清空了，但是并没有阻断消息的传播，导致空消息被传递给了nonebot_plugin_petpet，因此nonebot_plugin_petpet报错

现在ayaka（0.4.3）将优先级进一步降低到了20，并修复了清空消息的问题

ayaka_games也更新到了（0.3.4），同时修复了卖出mana失败的bug

你可以更新以解决此问题

`pip install nonebot-plugin-ayaka-games --upgrade`
