### ISSUE TITLE
游戏运行指令写在哪里？

### ISSUE THREAD

**Issue by carnzy** [bridgeL/nonebot-plugin-ayaka-games#9]

**Comment by bridgeL** [comment]
输入命令`#help`应该会显示所有插件的帮助

详细帮助文档 https://bridgel.github.io/ayaka_doc/latest/games/

**Comment by carnzy** [comment]
> 输入命令`#help`应该会显示所有插件的帮助
> 
> 详细帮助文档 https://bridgel.github.io/ayaka_doc/latest/games/

输入help无反应怎么办

**Comment by bridgeL** [comment]
可以看看启动bot时的运行截图吗？（记得隐私信息打码）

从bot启动到成功收到第一个消息为止

**Comment by carnzy** [comment]
> 可以看看启动bot时的运行截图吗？（记得隐私信息打码）
> 
> 从bot启动到成功收到第一个消息为止
![Snipaste_2022-12-17_16-37-39](https://user-images.githubusercontent.com/62609830/208233553-8fe1eb43-823b-416a-9749-4fdff7a4fda3.png)


[](url)

**Comment by bridgeL** [comment]
发送`#help`试试呢（加一个井号）？我刚才试了没找到问题

**Comment by carnzy** [comment]
> 可以看看启动bot时的运行截图吗？（记得隐私信息打码）
> 
> 从bot启动到成功收到第一个消息为止
![Snipaste_2022-12-17_16-42-16](https://user-images.githubusercontent.com/62609830/208233816-4c5a3a0d-a720-4820-a4b8-d601c5a38892.png)



> 可以看看启动bot时的运行截图吗？（记得隐私信息打码）
> 
> 从bot启动到成功收到第一个消息为止

![Snipaste_2022-12-17_16-42-45](https://user-images.githubusercontent.com/62609830/208233819-e86e1e43-4e0e-4626-b6fb-0e8064c3fa01.png)
![Snipaste_2022-12-17_16-43-00](https://user-images.githubusercontent.com/62609830/208233822-80db2870-ea97-41cd-ad47-2b01b9f6ac92.png)
![Snipaste_2022-12-17_16-43-38](https://user-images.githubusercontent.com/62609830/208233823-a9fd99ad-918a-4134-8074-06b90c9b17d6.png)
![Snipaste_2022-12-17_16-42-16](https://user-images.githubusercontent.com/62609830/208233833-4bcc8776-40c0-4520-8abc-e64c9d85777d.png)
![Snipaste_2022-12-17_16-42-45](https://user-images.githubusercontent.com/62609830/208233836-4f06997b-5303-430f-b840-246ef03105b5.png)
![Snipaste_2022-12-17_16-43-00](https://user-images.githubusercontent.com/62609830/208233837-f6799b74-58eb-49ab-9f60-268fa4dd2c8e.png)
![Snipaste_2022-12-17_16-43-38](https://user-images.githubusercontent.com/62609830/208233839-196d4713-f000-4e91-9852-72661cbc3ab7.png)

**Comment by carnzy** [comment]
> 发送`#help`试试呢（加一个井号）？我刚才试了没找到问题

![Snipaste_2022-12-17_16-48-50](https://user-images.githubusercontent.com/62609830/208234003-d5fbd1a8-adbc-4e4c-b4ff-4794e703d2ad.png)
依旧无响应

**Comment by bridgeL** [comment]
那安装最新版试试吧`pip install nonebot-plugin-ayaka-games==0.4.4`

**Comment by carnzy** [comment]
> 那安装最新版试试吧`pip install nonebot-plugin-ayaka-games==0.4.4`

help有响应了，但是游戏全无响应

**Comment by bridgeL** [comment]
那发送打开游戏的指令就可以了，比如你想玩24点，那就发送指令`24点`，不想玩了就发送`退出`或`强制退出`

还有一些游戏是不用打开，可以直接玩的，例如接龙，你直接发送`安步当车`，它识别到成语就会自动和你接龙

**Comment by bridgeL** [comment]
![image](https://user-images.githubusercontent.com/47290820/208234593-2382e3c0-ad00-4fcd-88e2-8b8af285d7aa.png)

详细的指令你可以看这里

https://bridgel.github.io/ayaka_doc/latest/games/help/

https://bridgel.github.io/ayaka_doc/latest/games/who-is-suspect/

**Comment by carnzy** [comment]
> ![image](https://user-images.githubusercontent.com/47290820/208234593-2382e3c0-ad00-4fcd-88e2-8b8af285d7aa.png)
> 
> 详细的指令你可以看这里
> 
> https://bridgel.github.io/ayaka_doc/latest/games/help/
> 
> https://bridgel.github.io/ayaka_doc/latest/games/who-is-suspect/

可以了，它每个指令都需要加井号

**Comment by bridgeL** [comment]
刚刚更新了帮助

如果不喜欢的话，可以改成自己习惯的配置，比如这里

https://bridgel.github.io/ayaka_doc/0.5.4/games/install/#_2

prefix设置为空字符串，就不需要每次加#了
